Draft: Add primitive onError
symmetryinvestments/concurrency pull request #40
Opened 2021-12-14 11:41 UTC by nordlow

2021-12-14 11:48 UTC, nordlow commented on source/concurrency/operations/onerror.d
> +        receiver.setError(() @trusted { return Throwable.chainTogether(e2, e); } ());
Shall we use `e2, e` or `e2, te` here?

2021-12-14 12:00 UTC, nordlow commented on source/concurrency/operations/onerror.d
> +  static assert(isThreadSafeFunction!SideEffect && is(typeof(effect(Exception.init)))); // TODO: is this ok?
Is this way of verifying the type of `effect` ok?

2021-12-14 12:00 UTC, nordlow commented on source/concurrency/operations/ontermination.d
> +  static assert(isThreadSafeFunction!SideEffect && is(typeof(effect()))); // TODO: is this ok?
Is this way of verifying the type of `effect` ok?

2021-12-14 12:28 UTC, skoppe requested changes

2021-12-14 12:28 UTC, skoppe commented on source/concurrency/operations/onerror.d
> +        receiver.setError(() @trusted { return Throwable.chainTogether(e2, e); } ());
I suppose chainTogether is @system because it deals with Throwables.

> It's best to use e2, e instead of e2, t here right?

I don't think it matters.

2021-12-14 12:28 UTC, skoppe commented on tests/ut/concurrency/operations.d
> +}
We should add a test case that throws in onError.

2021-12-14 12:28 UTC, skoppe commented on source/concurrency/operations/onerror.d
> +  static assert(isThreadSafeFunction!SideEffect && is(typeof(effect(Exception.init)))); // TODO: is this ok?
No, it leads to bad error message:

```
source/concurrency/operations/onerror.d(12,3): Error: static assert:  `isThreadSafeFunction!(int delegate() shared pure nothrow @nogc @safe) && is(typeof(effect(null)))` is false
```

whereas without it:

```
source/concurrency/operations/onerror.d(34,19): Error: delegate `this.sideEffect()` is not callable using argument types `(Exception)`
source/concurrency/operations/onerror.d(34,19):        expected 0 argument(s), not 1
source/concurrency/operations/onerror.d(50,30): Error: template instance `concurrency.operations.onerror.OnErrorReceiver!(void, int delegate() shared pure nothrow @nogc @safe, SyncWaitReceiver2!void)` error instantiating
source/concurrency/package.d(194,27):        instantiated from here: `connect!(SyncWaitReceiver2!void)`
source/concurrency/package.d(173,29):        instantiated from here: `syncWaitImpl!(OnErrorSender!(DoneSender, int delegate() shared pure nothrow @nogc @safe))`
tests/ut/concurrency/operations.d(440,62):        instantiated from here: `syncWait!(OnErrorSender!(DoneSender, int delegate() shared pure nothrow @nogc @safe))`
```

Granted, it isn't perfect either, but at least it shows you the `operations.d(440,62)`, and it explained why it couldn't call it.

To do better we have to static assert on effect taking a Throwable.

2021-12-14 12:28 UTC, skoppe commented on source/concurrency/operations/ontermination.d
> +  static assert(isThreadSafeFunction!SideEffect && is(typeof(effect()))); // TODO: is this ok?
Nah, it would leave it out.

2021-12-14 22:13 UTC, nordlow commented on source/concurrency/operations/onerror.d
> +        receiver.setError(() @trusted { return Throwable.chainTogether(e2, e); } ());
Ok. Closing this, then.

2021-12-14 22:14 UTC, nordlow commented on source/concurrency/operations/onerror.d
> +  static assert(isThreadSafeFunction!SideEffect && is(typeof(effect(Exception.init)))); // TODO: is this ok?
Ahh, yes. I remember now.

2021-12-14 22:15 UTC, nordlow commented on source/concurrency/operations/onerror.d
> +  static assert(isThreadSafeFunction!SideEffect && is(typeof(effect(Exception.init)))); // TODO: is this ok?
Ok, I'll revert.

2021-12-14 22:16 UTC, nordlow commented on source/concurrency/operations/ontermination.d
> +  static assert(isThreadSafeFunction!SideEffect && is(typeof(effect()))); // TODO: is this ok?
Ok. I'll revert.

2021-12-14 22:32 UTC, nordlow commented on tests/ut/concurrency/operations.d
> +}
Added at 75cec60.

2021-12-14 22:33 UTC, nordlow commented
I've adjusted according to your comments. I now wonder about 

```
@("onError.error_throw")
@safe unittest {
  import core.atomic : atomicOp;
  shared int g = 0;
  import core.exception : AssertError;
  ThrowingSender().onError((Exception e) @safe shared { throw new Exception(""); }).syncWait.isError.shouldThrow!(AssertError);
  g.should == 1;
}
```

doesn't what I thought it would. It instead errors during test running as


ut.concurrency.operations.onError.error_throw:
    tests/ut/concurrency/operations.d:458 - Expected: 1
    tests/ut/concurrency/operations.d:458 -      Got: 0
```

.

2021-12-15 09:24 UTC, skoppe commented
Ehh, maybe because you changed the g.atomicOp!"+="(1) with throw?

Also, why `AssertError` in `.isError.shouldThrow!(AssertError);`? That doesn't seem right.

- It should propagate the chained one.
- isError returns a boolean

2021-12-15 09:27 UTC, nordlow commented
> Ehh, maybe because you changed the g.atomicOp!"+="(1) with throw?

Ahh, I should keep that, right?

> Also, why `AssertError` in `.isError.shouldThrow!(AssertError);`? That doesn't seem right.

Ahh, sorry I should just use shouldThrow(), then.

> * It should propagate the chained one.

Should I check the structure of that chained exception?

> * isError returns a boolean

Are you saying I should something else instead of `isError`?

2021-12-15 09:32 UTC, nordlow commented
This now fails in

```d
.shouldThrow;
```

in

```d
@("onError.error_throw")
@safe unittest {
  import core.atomic : atomicOp;
  shared int g = 0;
  import core.exception : AssertError;
  ThrowingSender().onError((Exception e) @safe shared
                           {
                               g.atomicOp!"+="(1);
                               throw new Exception("");
                           })
                  .syncWait
                  .isError
                  .shouldThrow;
  g.should == 1;
}
```

as

```d
ut.concurrency.operations.onError.error_throw:
    tests/ut/concurrency/operations.d:464 - Expression threw core.exception.AssertError instead of the expected Exception:
Assertion failure
```

locally. I don't understand what's wrong.

2021-12-15 10:03 UTC, skoppe commented
> Ahh, I should keep that, right?

Nope, you can just test the exception

> Are you saying I should use something else instead of isError?

Maybe `assumeOk`? It will rethrow the error. Or perhaps just `.error` which will return the exception.

2021-12-15 10:29 UTC, nordlow commented
> > Ahh, I should keep that, right?
> 
> Nope, you can just test the exception
> 
> > Are you saying I should use something else instead of isError?
> 
> Maybe `assumeOk`? It will rethrow the error. Or perhaps just `.error` which will return the exception.

Do you mean

ThrowingSender().onError((Exception e) @safe shared
                           {
                               g.atomicOp!"+="(1);
                               throw new Exception("");
                           })
                  .syncWait
                  .assumeOk
                  .shouldThrow;

or

ThrowingSender().onError((Exception e) @safe shared
                           {
                               g.atomicOp!"+="(1);
                               throw new Exception("");
                           })
                  .syncWait
                  .error
                  .doSomethingWithError

?

2021-12-15 14:28 UTC, nordlow commented
> Maybe `assumeOk`? It will rethrow the error. Or perhaps just `.error` which will return the exception.

Thanks. This works:

```d
@safe unittest {
  import core.atomic : atomicOp;
  shared int g = 0;
  import core.exception : AssertError;
  ThrowingSender().onError((Exception e) @safe shared { g.atomicOp!"+="(1); throw new Exception(""); }).syncWait.assumeOk.shouldThrow!(AssertError);
  g.should == 1;
}
```

but I don't see how can I verify the structure of throwed chained exception because when I remove

```d
@safe unittest {
  import core.atomic : atomicOp;
  shared int g = 0;
  import core.exception : AssertError;
  ThrowingSender().onError((Exception e) @safe shared { g.atomicOp!"+="(1); throw new Exception(""); }).syncWait.assumeOk;
  g.should == 1;
}
```

gives

```
ut.concurrency.operations.onError.error_throw:
    source/concurrency/thread.d:147 - core.exception.AssertError@source/concurrency/thread.d(147): Assertion failure
----------------
??:? onAssertError [0x5624592135c1]
??:? _d_assertp [0x562459213582]
source/concurrency/thread.d:147 void concurrency.thread.LocalThreadWorker.start().__lambda19(std.variant.VariantN!(32uL).VariantN) [0x562459191625]
/home/per/.local/dlang/linux/bin64/src/phobos/std/concurrency.d:218 void std.concurrency.Message.map!(void function(std.variant.VariantN!(32uL).VariantN)*).map(void function(std.variant.VariantN!(32uL).VariantN)*) [0x5624591b366e]
/home/per/.local/dlang/linux/bin64/src/phobos/std/concurrency.d:2159 bool std.concurrency.MessageBox.get!(core.time.Duration, void function(std.variant.VariantN!(32uL).VariantN)*).get(core.time.Duration, scope void function(std.variant.VariantN!(32uL).VariantN)*).onStandardMsg(ref std.concurrency.Message) [0x5624591b2ffc]
/home/per/.local/dlang/linux/bin64/src/phobos/std/concurrency.d:2243 bool std.concurrency.MessageBox.get!(core.time.Duration, void function(std.variant.VariantN!(32uL).VariantN)*).get(core.time.Duration, scope void function(std.variant.VariantN!(32uL).VariantN)*).scan(ref std.concurrency.List!(std.concurrency.Message).List) [0x5624591b3427]
/home/per/.local/dlang/linux/bin64/src/phobos/std/concurrency.d:2286 bool std.concurrency.MessageBox.get!(core.time.Duration, void function(std.variant.VariantN!(32uL).VariantN)*).get(core.time.Duration, scope void function(std.variant.VariantN!(32uL).VariantN)*) [0x5624591b2d62]
/home/per/.local/dlang/linux/bin64/src/phobos/std/concurrency.d:990 bool std.concurrency.receiveTimeout!(void function(std.variant.VariantN!(32uL).VariantN)*).receiveTimeout(core.time.Duration, void function(std.variant.VariantN!(32uL).VariantN)*) [0x5624591b2cbd]
source/concurrency/thread.d:144 @trusted void concurrency.thread.LocalThreadWorker.start() [0x5624591913e7]
source/concurrency/package.d:197 @safe concurrency.Result!(void).Result concurrency.syncWaitImpl!(concurrency.operations.onerror.OnErrorSender!(concurrency.sender.ThrowingSender, void delegate(Exception) pure @safe shared).OnErrorSender).syncWaitImpl(scope ref concurrency.operations.onerror.OnErrorSender!(concurrency.sender.ThrowingSender, void delegate(Exception) pure @safe shared).OnErrorSender, concurrency.stoptoken.StopSource) [0x56245912ff4a]
source/concurrency/package.d:173 @safe concurrency.Result!(void).Result concurrency.syncWait!(concurrency.operations.onerror.OnErrorSender!(concurrency.sender.ThrowingSender, void delegate(Exception) pure @safe shared).OnErrorSender).syncWait(scope concurrency.operations.onerror.OnErrorSender!(concurrency.sender.ThrowingSender, void delegate(Exception) pure @safe shared).OnErrorSender) [0x56245912fe33]
tests/ut/concurrency/operations.d:457 @safe void ut.concurrency.operations.__unittest_L453_C7() [0x5624591d3437]
```

2021-12-16 15:09 UTC, merged