Add `retryWhen` operation
symmetryinvestments/concurrency pull request #61
Opened 2022-07-22 14:12 UTC by rmanthorpe

This corresponds to https://github.com/facebookexperimental/libunifex/blob/070435602799b3bbbf0eb9d1973e422462c85726/doc/api_reference.md#retry_whensender-source-invocableerror-handler---sender

2022-07-22 14:37 UTC, skoppe requested changes
Can you add an entry to the readme.md as well?

2022-07-22 14:37 UTC, skoppe commented on source/concurrency/operations/retrywhen.d
> +private struct RetryOp(Receiver, Sender, Logic) {
`RetryWhenOp`

2022-07-22 14:37 UTC, skoppe commented on source/concurrency/operations/retrywhen.d
> +      auto s = logic.failure(e);
I know the other code was forwarding the `Throwable`, but we really shouldn't.

If its a `Throwable` we should just call `receiver.setError(e)` directly, and only make the `logic.failure` call if its an `Exception`

2022-07-25 08:28 UTC, rmanthorpe commented
> Can you add an entry to the readme.md as well?

Yep, all done. This seems to do the trick now.

2022-07-25 12:24 UTC, John-Colvin commented
@nordlow can you do a review of this please?

2022-07-25 14:38 UTC, nordlow commented
Afaict, the naming `retryWhen` is unfortunate because retry also takes a `logic` template parameter. Have you considered an alternative naming? Can you give your motive for the naming of `retryWhen`? Afaict, a better naming would be something like `retryDeferred`.

2022-07-25 14:54 UTC, nordlow commented on source/concurrency/operations/retrywhen.d
> +private struct RetryWhenOp(Receiver, Sender, Logic) {
This could be realized as

```d
private alias RetryWhenOp(Receiver, Sender, Logic) = RetryWhenOp!(RetryReceiver, Sender, Logic);
```

given `RetryOp` is generalized to

```d
private struct RetryOp(SuperReceiver, Receiver, Sender, Logic) {
  alias Op = OpType!(Sender, SuperReceiver!(Receiver, Sender, Logic));
  Op op;
  @disable this(ref return scope typeof(this) rhs);
  @disable this(this);
  this(Sender sender, return SuperReceiver!(Receiver, Sender, Logic) receiver) @trusted scope {
    op = sender.connect(receiver);
  }
  void start() @trusted nothrow scope {
    op.start();
  }
}
```

and similarly for `RetrySender`.

2022-07-25 15:24 UTC, rmanthorpe commented
> Afaict, the naming `retryWhen` is unfortunate because retry also takes a `logic` template parameter. Have you considered an alternative naming? Can you give your motive for the naming of `retryWhen`? Afaict, a better naming would be something like `retryDeferred`.

The name comes from libunifex which inspired this library (see link in project description). I'd prefer to keep the names well aligned. The problem is `retry` is a simplified version of `retryWhen` and doesn't exist in libunifex. I think it is the equivalent of `retryWhen` returning a `VoidSender`.

2022-07-25 15:29 UTC, nordlow commented
I'm also missing a template restriction or static assert for the `logic` template parameter.

2022-07-25 15:41 UTC, rmanthorpe commented
> I'm also missing a template restriction or static assert for the `logic` template parameter of both `retry` and `retryWhen`.

Added for `retryWhen` but not touching `retry` in this PR so that is a separate matter.

2022-07-25 20:58 UTC, skoppe commented
I simplified things by splitting the receiver into a `SourceReceiver` and a `TriggerReceiver`. If the `SourceReceiver` gets an error it calls the `Logic.failure()`, connecting the returning `Sender` to a `TriggerReceiver`. If the `TriggerReceiver` gets a value, it re-starts the original sender and connects it to the `SourceReceiver`. Alternating until either the source completes, or the logic throws an exception.

Also got rid of connectHeap by putting the source/trigger operational state on the retrywhen operational base state.

Rewrote some of the tests to use a `ManualTimerWorker` to test the delay stuff.

2022-07-25 20:58 UTC, skoppe approved these changes

2022-07-25 21:03 UTC, merged

2022-07-25 21:09 UTC, skoppe commented
Added v4.12.0 tag